### ISSUE TITLE
Reduce noise in unit tests

### ISSUE THREAD

**Issue by jpsember** [jpsember/tokn#26]
This is a LOT of unnecessary noise for a failing unit test:

```
tokn> rake test:only
Run options: 

# Running tests:

[1/1] TestFilter#test_Filter = 0.00 s
  1) Error:
TestFilter#test_Filter:
RuntimeError: sample of failing test
    /Users/home/github_projects/tokn/test/test_filter.rb:49:in `test_Filter'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:1265:in `run'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit/testcase.rb:17:in `run'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:940:in `block in _run_suite'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:933:in `map'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:933:in `_run_suite'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit.rb:663:in `block in _run_suites'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit.rb:661:in `each'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit.rb:661:in `_run_suites'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:884:in `_run_anything'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:1092:in `run_tests'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:1079:in `block in _run'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:1078:in `each'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:1078:in `_run'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit.rb:27:in `run'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit.rb:780:in `run'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit.rb:372:in `block (2 levels) in autorun'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit.rb:33:in `run_once'
    /usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/test/unit.rb:371:in `block in autorun'

Finished tests in 0.005533s, 180.7338 tests/s, 0.0000 assertions/s.
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips

ruby -v: ruby 2.1.5p284 (2015-01-22 revision 49370) [x86_64-darwin13.0]
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0" "/usr/local/var/rbenv/versions/2.1.0-dev/lib/ruby/2.1.0/rake/rake_test_loader.rb" "test/test_filter.rb" ]

Tasks: TOP => test:only
(See full trace by running task with --trace)
tokn> 
```

**Comment by jpsember** [comment]
Somebody doesn't like criticism:

https://github.com/seattlerb/minitest/issues/459

**Comment by jpsember** [comment]
Did
```
gem install rake
```
...and now the tests aren't running properly...

**Comment by jpsember** [comment]
Upgrading to minitest seems to help...
http://blog.teamtreehouse.com/short-introduction-minitest

**Comment by jpsember** [comment]
Maybe helpful:

https://web.archive.org/web/20120701103558/http://cheat.errtheblog.com/s/minitest/1
